CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (30) NOT NULL,
    SEXO ENUM ('M','F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE) 
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM ('RES','COM','CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)

);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@GMAIL.COM','86465468');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@GMAIL.COM','38452964');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@GMAIL.COM','7897243');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'39455869');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@GMAIL.COM','12384568');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','CELIA@GMAIL.COM','97843873');

+-----------+--------+------+------------------+----------+
| IDCLIENTE | NOME   | SEXO | EMAIL            | CPF      |
+-----------+--------+------+------------------+----------+
|         1 | JOAO   | M    | JOAO@GMAIL.COM   | 86465468 |
|         2 | CARLOS | M    | CARLOS@GMAIL.COM | 38452964 |
|         3 | ANA    | F    | ANA@GMAIL.COM    | 7897243  |
|         4 | CLARA  | F    | NULL             | 39455869 |
|         5 | JORGE  | M    | JORGE@GMAIL.COM  | 12384568 |
|         6 | CELIA  | F    | CELIA@GMAIL.COM  | 97843873 |
+-----------+--------+------+------------------+----------+

